### PR TITLE
Assorted fixes

### PR DESCRIPTION
**Pull request by ulrikstrid**
I'm trying to use this in a small service in production and these are changes I find while setting it up.

I can split it out into multiple PRs later if you want to.

### CODE REVIEW

**Comment by rizo** [comment]
Hey! Happy to hear you're using this library. Let me know if you need any help or find any issues.

Thanks for all the corrections. No need to split them into separate PRs (unless you prefer to).

**Comment by rizo** [comment]
@ulrikstrid Let me know when the PR is ready for review. I can it's currently set to "draft".

**Comment by ulrikstrid** [comment]
It's ok to review now @rizo we're happily running it on production 👍

**Review by rizo — APPROVED** [review]

**Comment by rizo** [comment]
Thank you!

**Pull request merged**
